apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-aro-cluster
  title: Create an Azure Red Hat OpenShift (ARO) Cluster
  description: A self-service template to provision a new ARO cluster using Ansible.
  tags:
    - recommended
    - ansible
    - collection
spec:
  owner: platform-team
  type: service

  # This section defines the web form for the developer.
  parameters:
    - title: Cluster Configuration
      required:
        - cluster_name
      properties:
        cluster_name:
          title: Cluster Name
          type: string
          description: A unique name for the ARO cluster (e.g., my-team-aro-cluster).
        worker_node_count:
          title: Number of Worker Nodes
          type: integer
          description: The number of worker nodes for the cluster.
          default: 3
        template:
          title: Template ID
          type: integer
          description: A unique name for the ARO cluster (e.g., my-team-aro-cluster).
          default: 7
        token:
          title: Token
          type: string
          description: Oauth2 token
          ui:field: AAPTokenField
          ui:backstage:
            review:
              show: false

  # This section defines the actions to run after the form is submitted.
  steps:
    - id: trigger-ansible-job
      name: Launch ARO Deployment Job in AAP
      # This action makes a REST API call to your AAP instance.
      action: rhaap:launch-job-template
      input:
        token: ${{ parameters.token }}
        values:
          template:
            id: ${{ parameters.template }}
