apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-aro-cluster
  title: Create an Azure Red Hat OpenShift (ARO) Cluster
  description: A self-service template to provision a new ARO cluster using Ansible.
spec:
  owner: platform-team
  type: service

  # This section defines the web form for the developer.
  parameters:
    - title: Cluster Configuration
      required:
        - cluster_name
      properties:
        cluster_name:
          title: Cluster Name
          type: string
          description: A unique name for the ARO cluster (e.g., my-team-aro-cluster).
        worker_node_count:
          title: Number of Worker Nodes
          type: integer
          description: The number of worker nodes for the cluster.
          default: 3

  # This section defines the actions to run after the form is submitted.
  steps:
    - id: trigger-ansible-job
      name: Launch ARO Deployment Job in AAP
      # This action makes a REST API call to your AAP instance.
      action: http:request:dynamic
      input:
        provider: aap
        path: 'job_templates/123/launch/'
        method: 'POST'
        body:
          extra_vars:
            cluster_name: ${{ parameters.cluster_name }}
            worker_node_count: ${{ parameters.worker_node_count }}
